include:
  - project: 'devops/cicd'
    file: 'scripts/build-image.yml'

variables:
  DOMAIN: ${DOMAIN}
  IMAGE_TAG: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}${CI_COMMIT_SHORT_SHA}

stages:
  - build

build-image:
  stage: build
  dependencies: []
  extends: .build-images
  variables:
    APP_VERSION: ${CI_COMMIT_TAG}
    K8S_IMAGE: ${IMAGE_TAG}
  tags:
    - k8s-runner
